package org.opensrp.service;

import org.apache.http.util.TextUtils;
import org.joda.time.DateTime;
import org.opensrp.domain.Shipment;
import org.opensrp.repository.AllShipments;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class ShipmentService {

    private AllShipments allShipments;

    @Autowired
    public ShipmentService(AllShipments allShipments) {
        this.allShipments = allShipments;
    }

    public synchronized Shipment add(Shipment shipment) {
        //ASSUMPTION: Shipments with an id (Auto-generated by CouchDB) are already saved in CouchDB
        if (!TextUtils.isEmpty(shipment.getId())) {
            throw new IllegalArgumentException("Shipment object should not have id field populated. " +
                    "Alternatively, " + shipment.getId() + " already exists");
        }

        shipment.setDateCreated(new DateTime());
        allShipments.add(shipment);
        return shipment;
    }

}
