package org.opensrp.domain.postgres;

import java.util.Date;

public class Event {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.event.id
	 * @mbg.generated  Fri Apr 06 16:01:06 EAT 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.event.json
	 * @mbg.generated  Fri Apr 06 16:01:06 EAT 2018
	 */
	private Object json;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.event.date_deleted
	 * @mbg.generated  Fri Apr 06 16:01:06 EAT 2018
	 */
	private Date dateDeleted;
	private int memberCount;
	private String householdType;
	private String latrineStructure;
	private String waterSource;
	private String financialStatus;
	private int monthlyExpenditure;
	private String dateOfReg;
	private String providerId;
	private String team;
	private String eventType;
	private Long serverVersion;
	private String baseEntityId;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.event.id
	 * @return  the value of core.event.id
	 * @mbg.generated  Fri Apr 06 16:01:06 EAT 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.event.id
	 * @param id  the value for core.event.id
	 * @mbg.generated  Fri Apr 06 16:01:06 EAT 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.event.json
	 * @return  the value of core.event.json
	 * @mbg.generated  Fri Apr 06 16:01:06 EAT 2018
	 */
	public Object getJson() {
		return json;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.event.json
	 * @param json  the value for core.event.json
	 * @mbg.generated  Fri Apr 06 16:01:06 EAT 2018
	 */
	public void setJson(Object json) {
		this.json = json;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.event.date_deleted
	 * @return  the value of core.event.date_deleted
	 * @mbg.generated  Fri Apr 06 16:01:06 EAT 2018
	 */
	public Date getDateDeleted() {
		return dateDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.event.date_deleted
	 * @param dateDeleted  the value for core.event.date_deleted
	 * @mbg.generated  Fri Apr 06 16:01:06 EAT 2018
	 */
	public void setDateDeleted(Date dateDeleted) {
		this.dateDeleted = dateDeleted;
	}

	public int getMemberCount() {
		return memberCount;
	}

	public void setMemberCount(int memberCount) {
		this.memberCount = memberCount;
	}

	public String getHouseholdType() {
		return householdType;
	}

	public void setHouseholdType(String householdType) {
		this.householdType = householdType;
	}

	public String getLatrineStructure() {
		return latrineStructure;
	}

	public void setLatrineStructure(String latrineStructure) {
		this.latrineStructure = latrineStructure;
	}

	public String getWaterSource() {
		return waterSource;
	}

	public void setWaterSource(String waterSource) {
		this.waterSource = waterSource;
	}

	public String getFinancialStatus() {
		return financialStatus;
	}

	public void setFinancialStatus(String financialStatus) {
		this.financialStatus = financialStatus;
	}

	

	public int getMonthlyExpenditure() {
		return monthlyExpenditure;
	}

	public void setMonthlyExpenditure(int monthlyExpenditure) {
		this.monthlyExpenditure = monthlyExpenditure;
	}	

	public String getProviderId() {
		return providerId;
	}

	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}

	public String getTeam() {
		return team;
	}

	public void setTeam(String team) {
		this.team = team;
	}

	public String getEventType() {
		return eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	public Long getServerVersion() {
		return serverVersion;
	}

	public void setServerVersion(Long serverVersion) {
		this.serverVersion = serverVersion;
	}

	public String getBaseEntityId() {
		return baseEntityId;
	}

	public void setBaseEntityId(String baseEntityId) {
		this.baseEntityId = baseEntityId;
	}

	public String getDateOfReg() {
		return dateOfReg;
	}

	public void setDateOfReg(String dateOfReg) {
		this.dateOfReg = dateOfReg;
	}
	
}